# Generated by Django 5.2.5 on 2025-08-12 13:19

import django.db.models.deletion
import django_countries.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DurationType',
            fields=[
                ('name', models.CharField(max_length=128, unique=True)),
                ('duration_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Duration Type',
                'verbose_name_plural': 'Duration Types',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('base_price', models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('country', django_countries.fields.CountryField(default='IN', help_text='Product origin country', max_length=2)),
                ('is_approved', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'products',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('variant_name', models.CharField(max_length=128)),
                ('sku_id', models.CharField(blank=True, max_length=128, null=True)),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('variant_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('country', django_countries.fields.CountryField(default='IN', max_length=2)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='module.product')),
            ],
            options={
                'verbose_name': 'Product Variant',
                'verbose_name_plural': 'Product Variants',
                'ordering': ('product__name', 'variant_name'),
            },
        ),
        migrations.CreateModel(
            name='PriceVariant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=100)),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('duration_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module.durationtype')),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='module.productvariant')),
            ],
            options={
                'verbose_name': 'Price Variant',
                'verbose_name_plural': 'Price Variants',
                'ordering': ('product_variant__product__name', 'product_variant__variant_name'),
            },
        ),
    ]
