# Generated by Django 5.2.5 on 2025-08-12 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricevariant',
            name='duration_type',
            field=models.ForeignKey(db_column='duration_id', on_delete=django.db.models.deletion.CASCADE, to='module.durationtype'),
        ),
    ]
